-- CrEaTe TaBlE STUDENT(ID INT PRIMARY KEY, NAME VARCHAR(255));
-- create database if not exists SCHOOL;
-- USE school;
-- SHOW DATABASES;
-- CREATE TABLE IF NOT EXISTS Grades(STUDENT_ID INT, GRADE VARCHAR(255), PRIMARY KEY(STUDENT_ID));
-- SHOW TABLES FROM ScHoOl;
-- USE default;
-- CREATE TABLE GRADES(STUDENT_ID INT, GRADE VARCHAR(255), PRIMARY KEY(STUDENT_ID));

insert into student values (1, 'Alice');
INSERT INTO StUdEnT VALUES (2, 'Bob');
insert into GRADES values (1, 'A');
USE SCHOOL;
INSERT INTO grades VALUES (2, 'B');
USE default;

SELECT * FROM STUDENT;
select NAME from STUDENT where ID = 1;
SELECT STUDENT.NAME, GRADES.GRADE FROM STUDENT INNER JOIN GRADES ON STUDENT.ID = GRADES.STUDENT_ID;
