#!/usr/bin/env bash

set -euo pipefail

rows="${1:-10000}"
total_columns="${2:-500}"
output="${3:-scripts/check_all_queries_10000_rows_500_cols.sql}"
main_table="${4:-wide_500_cols}"
lookup_table="${5:-wide_lookup}"
expiry_table="${6:-expiry_probe}"

if [ "$rows" -lt 1 ]; then
  echo "rows must be >= 1" >&2
  exit 1
fi

if [ "$total_columns" -lt 2 ]; then
  echo "total_columns must be >= 2" >&2
  exit 1
fi

mkdir -p "$(dirname "$output")"

main_col_name() {
  printf "C%03d" "$1"
}

{
  printf -- "-- FlexQL validation script generated by scripts/generate_validation_sql.sh\n"
  printf -- "-- Run from the FlexQL client REPL with:\n"
  printf -- "-- SOURCE %s\n\n" "$output"

  printf "SHOW DATABASES;\n"
  printf "USE default;\n"
  printf "DROP TABLE IF EXISTS %s;\n" "$main_table"
  printf "DROP TABLE IF EXISTS %s;\n" "$lookup_table"
  printf "DROP TABLE IF EXISTS %s;\n" "$expiry_table"

  printf "CREATE TABLE IF NOT EXISTS %s(ID INT PRIMARY KEY" "$main_table"
  col=1
  while [ "$col" -lt "$total_columns" ]; do
    printf ", %s VARCHAR(255)" "$(main_col_name "$col")"
    col=$((col + 1))
  done
  printf ");\n"

  printf "CREATE TABLE IF NOT EXISTS %s(ID INT PRIMARY KEY, TAG VARCHAR(255), CREATED_AT DATETIME);\n" "$lookup_table"
  printf "CREATE TABLE IF NOT EXISTS %s(ID INT PRIMARY KEY, NAME VARCHAR(255));\n" "$expiry_table"
  printf "SHOW TABLES;\n"

  row=1
  while [ "$row" -le "$rows" ]; do
    printf "INSERT INTO %s VALUES (%d" "$main_table" "$row"
    col=1
    while [ "$col" -lt "$total_columns" ]; do
      printf ", 'r%05d_c%03d'" "$row" "$col"
      col=$((col + 1))
    done
    printf ");\n"

    printf "INSERT INTO %s VALUES (%d, 'tag_%05d', '2026-03-25 00:00:00');\n" "$lookup_table" "$row" "$row"
    row=$((row + 1))
  done

  printf "INSERT INTO %s VALUES (1, 'expired-row') EXPIRES AT '2000-01-01 00:00:00';\n" "$expiry_table"
  printf "SELECT * FROM %s WHERE ID = 1;\n" "$main_table"
  printf "SELECT * FROM %s WHERE ID = %d;\n" "$main_table" "$rows"
  printf "SELECT ID FROM %s WHERE %s = 'r%05d_c001';\n" "$main_table" "$(main_col_name 1)" "$rows"
  printf "SELECT %s.%s, %s.TAG FROM %s INNER JOIN %s ON %s.ID = %s.ID WHERE %s.ID = %d;\n" \
    "$main_table" "$(main_col_name 1)" "$lookup_table" \
    "$main_table" "$lookup_table" "$main_table" "$lookup_table" "$lookup_table" "$rows"
  printf "SELECT * FROM %s;\n" "$expiry_table"
  printf "SHOW TABLES FROM default;\n"
} > "$output"

printf "Generated %s with %s rows and %s columns\n" "$output" "$rows" "$total_columns"
